<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>TurnerSoftware.SitemapTools</RootNamespace>
    <AssemblyName>TurnerSoftware.SitemapTools</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SunamoExceptions" Version="*" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC;TurnerSoftware.SitemapTools;TurnerSoftware.SitemapTools.csproj</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC;TurnerSoftware.SitemapTools;TurnerSoftware.SitemapTools.csproj</DefineConstants>
  </PropertyGroup>
</Project>