<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <!--<PackageReference Include="" Version=""/>-->
    <Folder Include="Properties\">
    </Folder>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SunamoExceptions" Version="*" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC;SunamoGpx;SunamoGpx.csproj</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC;SunamoGpx;SunamoGpx.csproj</DefineConstants>
  </PropertyGroup>
</Project>