<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="_NotMine\MSBuild\Project.txt"></EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Solution.txt"></EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="_NotMine\Templating\Runtime\Class.txt"></EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0"></PackageReference>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0"></PackageReference>
    <PackageReference Include="System.Memory" Version="4.5.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\sunamoWithoutLocalDep\cl\cl.csproj" />
    <PackageReference Include="SunamoExceptions" Version="*" />
    <PackageReference Include="SunamoShared" Version="*" />
    <ProjectReference Include="..\FubuCore\FubuCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="_NotMine\Templating\RemoteOperations.cs"></Compile>
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
</Project>