<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <Authors>cdorst</Authors>
    <Description>Structure for package-project .csproj files</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>CDorst.Metaproject.PackageIndex.Structures.PackageProject</PackageId>
    <Version>2.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CDorst.DevOps.Primitives.NuGet" Version="4.0.0" />
    <PackageReference Include="CDorst.DevOps.Primitives.VisualStudio.Projects.Helpers.DotNetCore" Version="7.0.0" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
</Project>