<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <Authors>cdorst</Authors>
    <Description>Helper for parsing project information from a .csproj file</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>CDorst.Metaproject.PackageIndex.Functions.ParseCsprojFile</PackageId>
    <Version>1.0.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\sunamoWithoutDep\SunamoExceptions\SunamoExceptions.csproj" />
    <ProjectReference Include="..\..\sunamoWithoutDep\SunamoShared\SunamoShared.csproj" />
    <ProjectReference Include="..\Metaproject.PackageIndex.Structures.PackageProject\Metaproject.PackageIndex.Structures.PackageProject.csproj" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
</Project>