<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <Version>23.12.9.4</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="7.0.2" />
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC;SunamoBitLockerManager;SunamoBitLockerManager.csproj</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC;SunamoBitLockerManager;SunamoBitLockerManager.csproj</DefineConstants>
  </PropertyGroup>
</Project>